services:
  devbox:
    build: .
    hostname: devbox
    ports:
      - "2222:22"
    volumes:
      - ssh-host-keys:/etc/ssh/host_keys
      - dev-home:/home/dev

volumes:
  ssh-host-keys:
  dev-home:
